"""empty message

Revision ID: 17bee1f53a6d
Revises: fd494357b454
Create Date: 2019-09-28 08:48:15.565704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bee1f53a6d'
down_revision = 'fd494357b454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('observacao', sa.Text(), nullable=True))
    op.add_column('pedidos', sa.Column('servico', sa.String(), nullable=True))
    op.drop_column('pedidos', 'descricao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pedidos', 'servico')
    op.drop_column('pedidos', 'observacao')
    # ### end Alembic commands ###
