"""empty message

Revision ID: 30c07af4d8b0
Revises: e7ae2a000b6b
Create Date: 2019-08-24 19:48:01.621707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c07af4d8b0'
down_revision = 'e7ae2a000b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('preco', sa.Float(), nullable=True))
    op.add_column('pedidos', sa.Column('status_conclusao', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'status_conclusao')
    op.drop_column('pedidos', 'preco')
    # ### end Alembic commands ###
