"""empty message

Revision ID: fd494357b454
Revises: 519799061150
Create Date: 2019-09-25 19:33:31.889629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd494357b454'
down_revision = '519799061150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_item', sa.String(), nullable=True),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=True),
    sa.Column('quantidade_minimo', sa.Integer(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque')
    # ### end Alembic commands ###
